# Generated by Django 4.2.3 on 2023-07-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_remove_blog_comments_comment_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True, default="default.jpg", upload_to="blog_images/"
            ),
        ),
    ]
