# Generated by Django 4.2.3 on 2023-07-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_alter_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
