# Generated by Django 4.2.3 on 2023-07-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ghala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('start_price', models.IntegerField()),
                ('rent_price', models.IntegerField()),
                ('on_demand', models.BooleanField(default=False)),
                ('space_available', models.BooleanField(default=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Soko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=50, unique=True)),
                ('last_price', models.IntegerField()),
                ('current_price', models.IntegerField()),
                ('on_demand', models.BooleanField(default=False)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
            ],
        ),
    ]
