# Generated by Django 4.2.3 on 2023-07-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghala',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
