# Generated by Django 4.2.3 on 2023-07-14 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_ghala_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mysoko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_on', models.DateTimeField()),
                ('profit', models.IntegerField()),
                ('soko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.soko')),
            ],
        ),
        migrations.CreateModel(
            name='Myghala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bags_stored', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
                ('rented_on', models.DateTimeField()),
                ('ghala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ghala')),
            ],
        ),
    ]
