# Generated by Django 4.2.3 on 2023-07-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myghala',
            name='duration_of_storage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='myghala',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
