# Generated by Django 4.2.3 on 2023-07-14 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproducts', '0002_myghala_duration_of_storage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myghala',
            name='amount_paid',
        ),
    ]
