# Generated by Django 4.2.3 on 2023-07-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproducts', '0003_remove_myghala_amount_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysoko',
            name='profit',
        ),
        migrations.AddField(
            model_name='mysoko',
            name='bags_sold',
            field=models.IntegerField(null=True),
        ),
    ]
