# Generated by Django 4.2.3 on 2023-07-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ghala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('start_price', models.IntegerField()),
                ('rent_price', models.IntegerField()),
                ('on_demand', models.BooleanField(default=False)),
                ('space_available', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='./services/images')),
            ],
        ),
        migrations.CreateModel(
            name='Soko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(default='', max_length=50)),
                ('last_price', models.IntegerField(default=0)),
                ('current_price', models.IntegerField(default=0)),
                ('on_demand', models.BooleanField()),
                ('image', models.ImageField(upload_to='./services/images')),
            ],
        ),
    ]
