# Generated by Django 4.2.3 on 2023-07-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ghala",
            name="image",
            field=models.ImageField(
                default="default.jpg", upload_to="./services/images"
            ),
        ),
        migrations.AlterField(
            model_name="soko",
            name="image",
            field=models.ImageField(
                default="default.jpg", upload_to="./services/images"
            ),
        ),
    ]
