# Generated by Django 4.2.3 on 2023-07-23 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myproducts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myghala",
            name="date_rented",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="mysoko",
            name="date_sold",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
